apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
    control-plane: controller-manager
  name: infinispan-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
    control-plane: controller-manager
  name: infinispan-operator-controller-manager
  namespace: infinispan-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-leader-election-role
  namespace: infinispan-operator
rules:
  - apiGroups:
      - ""
      - coordination.k8s.io
    resources:
      - configmaps
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-manager-role
  namespace: infinispan-operator
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - secrets
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - infinispan.org
    resources:
      - backups
      - backups/finalizers
      - backups/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infinispan.org
    resources:
      - batches
      - batches/finalizers
      - batches/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infinispan.org
    resources:
      - caches
      - caches/finalizers
      - caches/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infinispan.org
    resources:
      - infinispans
      - infinispans/finalizers
      - infinispans/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infinispan.org
    resources:
      - restores
      - restores/finalizers
      - restores/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs:
      - get
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-manager-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-leader-election-rolebinding
  namespace: infinispan-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infinispan-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: infinispan-operator-controller-manager
    namespace: infinispan-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-manager-rolebinding
  namespace: infinispan-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infinispan-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: infinispan-operator-controller-manager
    namespace: infinispan-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infinispan-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: infinispan-operator-controller-manager
    namespace: infinispan-operator
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 632512e4.infinispan.org
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-manager-config
  namespace: infinispan-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-webhook-service
  namespace: infinispan-operator
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: infinispan-operator
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
    control-plane: controller-manager
  name: infinispan-operator-controller-manager
  namespace: infinispan-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: infinispan-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: infinispan-operator
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - operator
            - --leader-elect
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INFINISPAN_OPERAND_VERSIONS
              value: |-
                [
                  {
                    "upstream-version": "14.0.1",
                    "image": "quay.io/infinispan/server:14.0.1.Final"
                  },
                  {
                    "upstream-version": "14.0.6",
                    "image": "quay.io/infinispan/server:14.0.6.Final"
                  },
                  {
                    "upstream-version": "14.0.9",
                    "image": "quay.io/infinispan/server:14.0.9.Final"
                  },
                  {
                    "upstream-version": "14.0.13",
                    "image": "quay.io/infinispan/server:14.0.13.Final"
                  },
                  {
                    "upstream-version": "14.0.17",
                    "image": "quay.io/infinispan/server:14.0.17.Final"
                  },
                  {
                    "upstream-version": "14.0.19",
                    "image": "quay.io/infinispan/server:14.0.19.Final"
                  },
                  {
                    "upstream-version": "14.0.20",
                    "image": "quay.io/infinispan/server:14.0.20.Final"
                  },
                  {
                    "upstream-version": "14.0.21",
                    "image": "quay.io/infinispan/server:14.0.21.Final"
                  },
                  {
                    "upstream-version": "14.0.24",
                    "image": "quay.io/infinispan/server:14.0.24.Final"
                  },
                  {
                    "upstream-version": "14.0.27",
                    "image": "quay.io/infinispan/server:14.0.27.Final"
                  },
                  {
                    "upstream-version": "14.0.32",
                    "image": "quay.io/infinispan/server:14.0.32.Final"
                  },
                  {
                    "upstream-version": "15.0.0",
                    "image": "quay.io/infinispan/server:15.0.0.Final"
                  },
                  {
                    "upstream-version": "15.0.3",
                    "image": "quay.io/infinispan/server:15.0.3.Final"
                  },
                  {
                    "upstream-version": "15.0.4",
                    "image": "quay.io/infinispan/server:15.0.4.Final"
                  },
                  {
                    "upstream-version": "15.0.5",
                    "image": "quay.io/infinispan/server:15.0.5.Final"
                  },
                  {
                    "upstream-version": "15.0.8",
                    "image": "quay.io/infinispan/server:15.0.8.Final"
                  },
                  {
                    "upstream-version": "15.0.10",
                    "image": "quay.io/infinispan/server:15.0.10.Final"
                  },
                  {
                    "upstream-version": "15.0.11",
                    "image": "quay.io/infinispan/server:15.0.11.Final"
                  },
                  {
                    "upstream-version": "15.0.13",
                    "image": "quay.io/infinispan/server:15.0.13.Final"
                  },
                  {
                    "upstream-version": "15.0.14",
                    "image": "quay.io/infinispan/server:15.0.14.Final"
                  },
                  {
                    "upstream-version": "15.1.0",
                    "image": "quay.io/infinispan/server:15.1.0.Final"
                  },
                  {
                    "upstream-version": "15.1.1",
                    "image": "quay.io/infinispan/server:15.1.1.Final"
                  },
                  {
                    "upstream-version": "15.1.3",
                    "image": "quay.io/infinispan/server:15.1.3.Final"
                  },
                  {
                    "upstream-version": "15.1.4",
                    "image": "quay.io/infinispan/server:15.1.4.Final"
                  },
                  {
                    "upstream-version": "15.1.5",
                    "image": "quay.io/infinispan/server:15.1.5.Final"
                  },
                  {
                    "upstream-version": "15.1.7",
                    "image": "quay.io/infinispan/server:15.1.7.Final"
                  },
                  {
                    "upstream-version": "15.2.1",
                    "image": "quay.io/infinispan/server:15.2.1.Final"
                  }
                ]
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: quay.io/infinispan/operator:2.4.12.Final
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      serviceAccountName: infinispan-operator-controller-manager
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-serving-cert
  namespace: infinispan-operator
spec:
  dnsNames:
    - infinispan-operator-webhook-service.infinispan-operator.svc
    - infinispan-operator-webhook-service.infinispan-operator.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: infinispan-operator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-selfsigned-issuer
  namespace: infinispan-operator
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: infinispan-operator/infinispan-operator-serving-cert
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /mutate-infinispan-org-v1-infinispan
    failurePolicy: Fail
    name: minfinispan.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - infinispans
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /mutate-infinispan-org-v2alpha1-backup
    failurePolicy: Fail
    name: mbackup.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backups
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /mutate-infinispan-org-v2alpha1-cache
    failurePolicy: Fail
    name: mcache.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - caches
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /mutate-infinispan-org-v2alpha1-restore
    failurePolicy: Fail
    name: mrestore.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - restores
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: infinispan-operator/infinispan-operator-serving-cert
  labels:
    app.kubernetes.io/name: infinispan-operator
  name: infinispan-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /validate-infinispan-org-v1-infinispan
    failurePolicy: Fail
    name: vinfinispan.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - infinispans
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /validate-infinispan-org-v2alpha1-backup
    failurePolicy: Fail
    name: vbackup.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - backups
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /validate-infinispan-org-v2alpha1-batch
    failurePolicy: Fail
    name: vbatch.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - batches
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /validate-infinispan-org-v2alpha1-cache
    failurePolicy: Fail
    name: vcache.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - caches
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: infinispan-operator-webhook-service
        namespace: infinispan-operator
        path: /validate-infinispan-org-v2alpha1-restore
    failurePolicy: Fail
    name: vrestore.kb.io
    rules:
      - apiGroups:
          - infinispan.org
        apiVersions:
          - v2alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - restores
    sideEffects: None
